v0.3.0~pre2

diff --git a/free-pmx-no-subscription/bin/no-subscription b/free-pmx-no-subscription/bin/no-subscription
--- a/free-pmx-no-subscription/bin/no-subscription
+++ b/free-pmx-no-subscription/bin/no-subscription
@@ -13,9 +13,10 @@ source "/usr/lib/free-pmx/no-subscription-common" 2> /dev/null \
 
 init "FREE_PMX_NO_SUBSCRIPTION" "$@"
 
-declare_apt_lists
+{ declare_aptsrcs; declare -i err=$?; }
+(( err & 1 )) && { echo "Cannot gather necessary system information, aborting." >&2; exit 1; }
 
-{ declare -A todo_id_flags; for i in "${ORD_LIST_IDS[@]}"; do todo_id_flags["$i"]=0; done; }
+{ declare -A todo_id_flags; for i in "${ORD_APTSRC_IDS[@]}"; do todo_id_flags["$i"]=0; done; }
 
 if [[ -n $O_TARGET ]]; then
     (( ${#ARGS[@]} == 0 )) \
@@ -23,8 +24,8 @@ if [[ -n $O_TARGET ]]; then
 
     declare list_id_match=''
 
-    for i in "${!APT_LISTS[@]}"; do
-        [[ $O_TARGET == "${APT_LISTS["$i"]}" ]] \
+    for i in "${!APTSRC_TARGETS[@]}"; do
+        [[ $O_TARGET == "${APTSRC_TARGETS["$i"]}" ]] \
         && { list_id_match="$i"; todo_id_flags["$i"]=1; break; }
     done
 
@@ -41,56 +42,51 @@ elif (( ${#ARGS[@]} > 0 )); then
         esac
     done
 else
-    echo -n "Detecting default lists ..."
-    for i in "${ORD_LIST_IDS[@]}"; do
-        [[ -f ${APT_LISTS["$i"]} ]] && todo_id_flags["$i"]=1 && echo -n " $i"
+    echo -n "Detecting default sources ..."
+    for i in "${ORD_APTSRC_IDS[@]}"; do
+        [[ -f ${APTSRC_TARGETS["$i"]} ]] && todo_id_flags["$i"]=1 && echo -n " $i"
     done
     echo        
 fi
 
-{ todo_count=0; for i in "${ORD_LIST_IDS[@]}"; do (( todo_count+=todo_id_flags[$i] )); done; }
+{ todo_count=0; for i in "${ORD_APTSRC_IDS[@]}"; do (( todo_count+=todo_id_flags[$i] )); done; }
 done_count=0
 
 if (( todo_count > 0 )); then
-    { declare_ns_repos; declare -i err=$?; }
-    (( err & 1 )) \
-    && { echo "Cannot assemble repository lists, aborting." >&2; exit 1; }
-    (( err & 2 )) && (( todo_id_flags["ceph"] == 1 )) \
+    (( todo_id_flags["ceph"] == 1 )) && [[ -z $FREE_PMX_CEPH ]] \
     && { todo_id_flags["ceph"]=0; echo "Ceph codename not configured, skipping ..." >&2; }
 
-    for i in "${ORD_LIST_IDS[@]}"; do
+    for i in "${ORD_APTSRC_IDS[@]}"; do
         (( todo_id_flags["$i"] == 1 )) \
         && echo "Setting up for $i ..." \
-        && run_rl_replace "${APT_LISTS["$i"]}" "${APT_LISTS_NEW["$i"]}" "${NS_REPOS["$i"]}" \
+        && run_rl_replace "${APTSRC_TARGETS["$i"]}" "${APTSRC_TEMPLS["$i"]}" \
         && (( done_count++ ))
     done
     (( done_count != todo_count )) && status=1
 
     echo "Completed total $done_count of $todo_count."
-
     echo
 
-    echo "Checking for Proxmox release key: $REPOS_KEY_LOCAL ..."
-    run_rk_check "$REPOS_KEY_LOCAL" "$REPOS_KEY_ORIGIN" \
+    echo "Checking for Proxmox release key: $FREE_PMX_APTKEY_LOCAL ..."
+    run_rk_check "$FREE_PMX_APTKEY_LOCAL" "$FREE_PMX_APTKEY_ORIGIN" \
     || { echo "Failed Proxmox release key check." >&2; status=1; }
 else
     echo "Nothing to be set up."
 fi
 
-if (( O_AUTORUN == 0 )) && (( done_count > 0 )); then
-    echo
-    echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    echo "NOTICE: Do not forget to perform UPDATE and UPGRADE, e.g.:"
-    echo
-    echo "  apt update"
-    echo "  apt full-upgrade"
-fi
+(( O_AUTORUN == 0 )) && (( done_count > 0 )) && cat << 'EOF'
 
-if (( O_AUTORUN == 0 )); then
-    echo
-    echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-    echo "Visit <https://free-pmx.pages.dev/tools/free-pmx-no-subscription/>"
-    echo "for more details, to check the latest version or to report an issue."
-fi
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+NOTICE: Do not forget to perform UPDATE and UPGRADE, e.g.:
+    apt update
+    apt full-upgrade
+EOF
+
+(( O_AUTORUN == 0 )) && cat << 'EOF'
+
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+Visit <https://free-pmx.pages.dev/tools/free-pmx-no-subscription/>
+for more details, to check the latest version or to report an issue.
+EOF
 
 exit $status
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common b/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common
--- a/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common
@@ -1,53 +1,51 @@
 # SPDX-License-Identifier: AGPL-3.0-only
 
+source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
+|| { echo "Internal error, aborting." >&2; exit 1; }
+
 declare_common() {
 
       declare -rg NS_CONFIG="/etc/free-pmx/no-subscription.conf"
 
 }
 
-declare_apt_lists() {
+declare_aptsrcs() {
 
-      declare -rg ORD_LIST_IDS=("pve" "pbs" "pmg" "ceph")
+      declare -rg ORD_APTSRC_IDS=("pve" "pbs" "pmg" "ceph")
+
+      declare -A os_release
+      source_kv "/etc/os-release" os_release VERSION_ID VERSION_CODENAME \
+      && check_kv_allset os_release VERSION_ID VERSION_CODENAME \
+      || return 1
+
+      [[ ${os_release[VERSION_ID]} =~ ^[0-9]+$ ]] || return 1
+      declare -r formats=(sources list)
+      declare -rg APTSRC_FORMAT="${formats[(( os_release[VERSION_ID] < 13 ))]}"
 
       declare -r list_d="/etc/apt/sources.list.d"
 
-      declare -rgA APT_LISTS=(
-            ["pve"]="$list_d/pve-enterprise.list"
-            ["pbs"]="$list_d/pbs-enterprise.list"
-            ["pmg"]="$list_d/pmg-enterprise.list"
-            ["ceph"]="$list_d/ceph.list"
+      declare -rgA APTSRC_TARGETS=(
+            ["pve"]="$list_d/pve-enterprise.$APTSRC_FORMAT"
+            ["pbs"]="$list_d/pbs-enterprise.$APTSRC_FORMAT"
+            ["pmg"]="$list_d/pmg-enterprise.$APTSRC_FORMAT"
+            ["ceph"]="$list_d/ceph.$APTSRC_FORMAT"
       )
 
-      declare -rgA APT_LISTS_NEW=(
-            ["pve"]="$list_d/pve-no-subscription.list"
-            ["pbs"]="$list_d/pbs-no-subscription.list"
-            ["pmg"]="$list_d/pmg-no-subscription.list"            
-            ["ceph"]="$list_d/ceph-no-subscription.list"
+      declare -r templ_d="/usr/share/free-pmx/no-subscription-aptsrcs"
+
+      declare -rgA APTSRC_TEMPLS=(
+            ["pve"]="$templ_d/pve-no-subscription.$APTSRC_FORMAT.template"
+            ["pbs"]="$templ_d/pbs-no-subscription.$APTSRC_FORMAT.template"
+            ["pmg"]="$templ_d/pmg-no-subscription.$APTSRC_FORMAT.template"
+            ["ceph"]="$templ_d/ceph-no-subscription.$APTSRC_FORMAT.template"
       )
 
-}
+      declare -rgx FREE_PMX_DEBIAN="${os_release[VERSION_CODENAME]}"
+      declare -rgx FREE_PMX_CEPH
 
-declare_ns_repos() {
-
-      declare -i err=0
-
-      DEBIAN=$( source "/etc/os-release" 2> /dev/null ||:; echo "$VERSION_CODENAME"; )
-      [[ -z $DEBIAN ]] && { echo "Could not determine Debian version codename."; return $(( err | 1 )); }
-
-      [[ -z $FREE_PMX_CEPH ]] && err=$(( err | 2 ))
-
-      declare -rgA NS_REPOS=(
-            ["pve"]="deb http://download.proxmox.com/debian/pve $DEBIAN pve-no-subscription"
-            ["pbs"]="deb http://download.proxmox.com/debian/pbs $DEBIAN pbs-no-subscription"
-            ["pmg"]="deb http://download.proxmox.com/debian/pmg $DEBIAN pmg-no-subscription"
-            ["ceph"]="deb http://download.proxmox.com/debian/ceph-$FREE_PMX_CEPH $DEBIAN no-subscription"
-      )
-
-      declare -rg REPOS_KEY_LOCAL="/etc/apt/trusted.gpg.d/proxmox-release-$DEBIAN.gpg"
-      declare -rg REPOS_KEY_ORIGIN="https://enterprise.proxmox.com/debian/proxmox-release-$DEBIAN.gpg"
-
-      return $err
+      declare -rgx FREE_PMX_APTKEY_SHARE="/usr/share/keyrings/proxmox-archive-keyring.gpg"
+      declare -rgx FREE_PMX_APTKEY_LOCAL="/etc/apt/keyrings/proxmox-release-$FREE_PMX_DEBIAN.gpg"
+      declare -rgx FREE_PMX_APTKEY_ORIGIN="https://enterprise.proxmox.com/debian/proxmox-release-$FREE_PMX_DEBIAN.gpg"
 
 }
 
@@ -58,6 +56,7 @@ declare_patchdefs() {
       declare -rga AVAIL_PATCH_TARGETS=(
             "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
             "/usr/share/pve-manager/js/pvemanagerlib.js"
+            "/usr/share/pve-manager/touch/pvemanager-mobile.js"
             "/usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js"
             "/usr/share/javascript/pmg-gui/js/pmgmanagerlib.js"
       )
@@ -68,21 +67,19 @@ declare_patchdefs() {
       declare -gA PATCHDEF_TARGETS
 
       for p in "${PATCHDEF_DIR}/"*.patchdef; do
-            unset _PD_TGT_
-            raw() { return; }
-            source "$p" 2> /dev/null || { err=$(( err | 1 )); continue; }
-            unset raw
-            [ -z "$_PD_TGT_" ] && { err=$(( err | 2 )); continue; }
+            declare -A pd
+            source_kv "$p" pd TARGET || { err=$(( err | 1 )); continue; }
+            [ -z "${pd[TARGET]}" ] && { err=$(( err | 2 )); continue; }
 
             if [[ "$p" =~ ^${PATCHDEF_DIR}/(.*)\.patchdef ]]; then            
                   declare m=${BASH_REMATCH[1]}
                   ORD_PATCHDEF_IDS+=("$m")
-                  PATCHDEF_TARGETS["$m"]="$_PD_TGT_" 
+                  PATCHDEF_TARGETS["$m"]="${pd[TARGET]}" 
             fi
       done
 
-      declare -r ORD_PATCHDEF_IDS
-      declare -r PATCHDEF_TARGETS
+      declare -rg ORD_PATCHDEF_IDS
+      declare -rg PATCHDEF_TARGETS
 
       return $err
 
@@ -132,9 +129,9 @@ init() {
 
       { shift $((OPTIND-1)); while (($# > 0)); do ARGS+=("$1"); shift; done; }
 
-      declare -r O_AUTORUN
-      declare -r O_TARGET
-      declare -r ARGS
+      declare -rg O_AUTORUN
+      declare -rg O_TARGET
+      declare -rg ARGS
 
 }
 
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply b/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply
--- a/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply
@@ -2,48 +2,60 @@
 
 # SPDX-License-Identifier: AGPL-3.0-only
 
-set -o pipefail
+source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
+|| { echo "Internal error, aborting." >&2; exit 1; }
 
 declare -i status=0
 
 [[ -n $1 ]] && declare -r patchdef=$1 || exit 1
 declare -r bak_ext=$2
 
-unset _PD_DISP_ _PD_TGT_ _PD_ORIG_ _PD_REPL_
-raw() { IFS='' read -d '' -r "$1" ||:; }
-source "$patchdef" 2> /dev/null \
+declare -A pd
+source_kv "$patchdef" pd DISPLAY TARGET PACKAGE SINCE \
+&& check_kv_allset pd DISPLAY TARGET PACKAGE SINCE \
 || { echo "! Corrupt patch definition: $patchdef" >&2; exit $(( status | 1 )); }
-unset raw
 
-[[ -n $_PD_DISP_ ]] && [[ -n $_PD_TGT_ ]] && [[ -n $_PD_ORIG_ ]] && [[ -n $_PD_REPL_ ]] \
-|| { echo "! Invalid patch definition: $patchdef" >&2; exit $(( status | 1 )); }
+[[ -f ${pd[TARGET]} ]] \
+|| { echo "! File to patch not present for: ${pd[DISPLAY]}" >&2; exit $(( status | 2 )); }
 
-[[ -f $_PD_TGT_ ]] \
-|| { echo "! File to patch not present for: $_PD_DISP_" >&2; exit $(( status | 2 )); }
+declare pd_version
+pd_version=$(deb_last_le_version "${pd[PACKAGE]}" "${pd[SINCE]}") \
+|| { echo "! Cannot determine appropriate patch version: $patchdef" >&2; exit $(( status | 4 )); }
+
+declare pd_partial="${patchdef%*.patchdef}.$pd_version"
+
+declare -A pd_rawblock
+slurp "$pd_partial".orig 'pd_rawblock[ORIG]' \
+&& slurp "$pd_partial".repl 'pd_rawblock[REPL]' \
+|| { echo "! Error loading patch partials: $pd_partial.{orig,repl}" >&2; exit $(( status | 4 )); }
 
 if [[ -n $bak_ext ]]; then
-    cp "$_PD_TGT_"{,."$bak_ext"} 2> /dev/null \
-    || echo "! Unable to make a '.$bak_ext' copy: $_PD_TGT_" >&2
+    cp "${pd[TARGET]}"{,."$bak_ext"} 2> /dev/null \
+    || echo "! Unable to make a '.$bak_ext' copy: ${pd[TARGET]}" >&2
 fi
 
-declare checksum_prior=$(sha512sum "$_PD_TGT_" 2> /dev/null | awk '{print $1}') \
-|| unset checksum_prior
+declare tfile checksum_prior checksum_after
 
-export _PD_ORIG_ _PD_REPL_
-perl -pi -e 'BEGIN { undef $/; $o = quotemeta($ENV{_PD_ORIG_}); $r = $ENV{_PD_REPL_}; } s/$o/$r/;' "$_PD_TGT_" 2> /dev/null \
-|| { echo "! Error during patch application: $_PD_DISP_" >&2; exit $(( status | 2 )); }
+checksum_prior=$(checksum "${pd[TARGET]}")
 
-declare checksum_after=$(sha512sum "$_PD_TGT_" 2> /dev/null | awk '{print $1}') \
-|| unset checksum_after
+{
+tfile=$(mktemp /tmp/free_pmx_patched_XXXXXX) \
+&& chmod 644 "$tfile" \
+&& subst_rawblock pd_rawblock < "${pd[TARGET]}" > "$tfile" \
+&& mv -f "$tfile" "${pd[TARGET]}"; \
+} 2> /dev/null \
+|| { echo "! Error during patch application: ${pd[DISPLAY]}" >&2; exit $(( status | 2 )); }
+
+checksum_after=$(checksum "${pd[TARGET]}")
 
 if [[ -z $checksum_prior ]] || [[ -z $checksum_after ]]; then
-    echo "? Unknown result: $_PD_DISP_"
+    echo "? Unknown result: ${pd[DISPLAY]}"
     status=$(( status | 4 ))
 elif [[ $checksum_prior == "$checksum_after" ]]; then
-    echo "- NO effect: $_PD_DISP_"
+    echo "- NO effect: ${pd[DISPLAY]}"
     status=$(( status | 8 ))
 else
-    echo "+ OK: $_PD_DISP_"
+    echo "+ OK: ${pd[DISPLAY]}"
 fi
 
 exit $status
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check b/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check
--- a/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check
@@ -2,7 +2,8 @@
 
 # SPDX-License-Identifier: AGPL-3.0-only
 
-set -o pipefail
+source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
+|| { echo "Internal error, aborting." >&2; exit 1; }
 
 declare -i status=0
 
@@ -29,7 +30,12 @@ gpg --show-keys "$repo_key" 2> /dev/null \
 
 [[ -d "$GNUPGHOME" ]] && rm -rf "$GNUPGHOME" 2> /dev/null
 
-{ sha512sum "$repo_key" | awk '{print "sha512 " $1}'; } 2> /dev/null \
-|| { echo "! Errors calculating key checksum." >&2; status=1; }
+declare checksum
+if checksum=$(checksum "$repo_key" 512); then
+    echo "sha512 $checksum"
+else
+    echo "! Errors calculating key checksum." >&2
+    status=1
+fi
 
 exit $status
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace b/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace
--- a/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace
@@ -2,27 +2,37 @@
 
 # SPDX-License-Identifier: AGPL-3.0-only
 
+source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
+|| { echo "Internal error, aborting." >&2; exit 1; }
+
 declare -i status=0
 
-[[ -n $1 ]] && declare -r old_list=$1 || exit 1
-[[ -n $2 ]] && declare -r new_list=$2 || exit 1
-[[ -n $3 ]] && declare -r new_source=$3 || exit 1
+[[ -n $1 ]] && declare -r orig=$1 || exit 1
+[[ -n $2 ]] && declare -r templ=$2 || exit 1
 
-if [[ ! -f $old_list ]]; then
-    echo "~ Original not present: $old_list"
-elif mv "$old_list"{,.disabled} 2> /dev/null; then
-    echo "+ Disabled original: $old_list"
+[[ -n $FREE_PMX_DEBIAN ]] || exit 2
+
+if [[ ! -f $orig ]]; then
+    echo "~ Original not present: $orig"
+elif mv "$orig"{,.disabled} 2> /dev/null; then
+    echo "+ Disabled original: $orig"
 else
-    echo "! Could not disable original: $old_list" >&2
+    echo "! Could not disable original: $orig" >&2
     status=1
 fi
 
-if [[ -f $new_list ]]; then
-    echo "~ New NOT created as already present: $new_list"
-elif { cat > "$new_list" <<< "$new_source"; } 2> /dev/null; then
-    echo "+ Created new: $new_list"
+declare dir="${orig%/*}"
+declare templ_name="${templ##*/}"
+declare repl_name="${templ_name%.template}"
+declare repl="$dir/$repl_name"
+declare -a vars=(FREE_PMX_{DEBIAN,CEPH,APTKEY_SHARE,APTKEY_LOCAL})
+
+if [[ -f $repl ]]; then
+    echo "~ New NOT created as already present: $repl"
+elif { subst_vars "${vars[@]}" < "$templ" > "$repl"; } 2> /dev/null; then
+    echo "+ Created new: $repl"
 else
-    echo "! Could not create: $new_list" >&2
+    echo "! Could not create: $repl" >&2
     status=1
 fi
 
