v0.3.3

diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/aptsrc-replace b/free-pmx-no-subscription/usr/lib/free-pmx/aptsrc-replace
--- a/free-pmx-no-subscription/usr/lib/free-pmx/aptsrc-replace
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/aptsrc-replace
@@ -9,32 +9,42 @@ source "/usr/lib/free-pmx/no-subscription-util" \
     && init_out \
     || exit 255
 
-[[ -n $1 ]] && declare -r orig=$1 || exit 1
-[[ -n $2 ]] && declare -r templ=$2 || exit 1
+[[ -n $1 ]] && declare -r aptsrcdef=$1 || exit 1
 
-[[ -n $FREE_PMX_DEBIAN ]] || exit 2
+[[ -n $FREE_PMX_APTEXT ]] && [[ -n $FREE_PMX_DEBIAN ]] || exit 2
 
-if [[ ! -f $orig ]]; then
-    print OUT "~ Original not present: $orig"
-elif mv "$orig"{,.disabled}; then
-    print OUT "+ Disabled original: $orig"
+declare -ra asd_vars=(DISABLE CREATE FROM URI SUITE COMPONENT KEY)
+declare -A asd
+source_kv "$aptsrcdef" asd "${asd_vars[@]}" \
+    && check_kv_allset asd "${asd_vars[@]}" \
+    || {
+        print ERR "! Corrupt source definition: $aptsrcdef"
+        exit $((status |= 1))
+    }
+
+if [[ ! -f ${asd[DISABLE]} ]]; then
+    print OUT "~ Original not present: ${asd[DISABLE]}"
+elif mv "${asd[DISABLE]}"{,.disabled}; then
+    print OUT "+ Disabled original: ${asd[DISABLE]}"
 else
-    print ERR "! Could not disable original: $orig"
+    print ERR "! Could not disable original: ${asd[DISABLE]}"
     ((status |= 1))
 fi
 
-declare dir="${orig%/*}"
-declare templ_name="${templ##*/}"
-declare repl_name="${templ_name%.template}"
-declare repl="$dir/$repl_name"
-declare -a vars=(FREE_PMX_{DEBIAN,CEPH,APTKEY})
+declare policy
+if ! policy=$(apt_policy_match "${asd[URI]}" "${asd[SUITE]}" "${asd[COMPONENT]}"); then
+    print ERR "! Unable to check APT policy for duplicates."
+    ((status |= 1))
+elif [[ -n $policy ]]; then
+    print OUT "~ New NOT created as same record already exists as per APT policy:"
+    print OUT "  $policy"
+elif subst_props asd URI SUITE COMPONENT KEY \
+    < "${aptsrcdef%/*}/${asd[FROM]}" \
+    > "${asd[CREATE]}"; then
 
-if [[ -f $repl ]]; then
-    print OUT "~ New NOT created as already present: $repl"
-elif subst_vars "${vars[@]}" < "$templ" > "$repl"; then
-    print OUT "+ Created new: $repl"
+    print OUT "+ Created new: ${asd[CREATE]}"
 else
-    print ERR "! Could not create: $repl"
+    print ERR "! Could not create: ${asd[CREATE]}"
     ((status |= 1))
 fi
 
