v0.3.0

diff --git a/free-pmx-no-subscription/DEBIAN/postinst b/free-pmx-no-subscription/DEBIAN/postinst
--- a/free-pmx-no-subscription/DEBIAN/postinst
+++ b/free-pmx-no-subscription/DEBIAN/postinst
@@ -1,52 +1,44 @@
 #!/bin/bash
 set -e
 
+source "/usr/lib/free-pmx/no-subscription-common" \
+    && declare_ns_globals \
+    && declare_nn_globals \
+    || {
+        echo "ERROR: ${0##*/} - auto-run skipped." >&2
+        exit 0
+    }
+
 case "$1" in
-    configure)
 
-		no-subscription -a || echo "ISSUES reported: $1" >&2
-		no-nag -a || echo "ISSUES reported: $1" >&2
+configure)
 
+    no-subscription -a || echo "ISSUES reported: $1" >&2
+    no-nag -a || echo "ISSUES reported: $1" >&2
     ;;
 
-    triggered)
+triggered)
 
-        for t in $2; do
+    for t in $2; do
 
-            case "$t" in
+        if [[ -v APTSRC_TARGET_TO_ID[$t] ]]; then
+            no-subscription -at "$t" || echo "ISSUES reported: $1 $t" >&2
+        elif [[ -v PATCHDEF_TARGET_TO_IDS[$t] ]]; then
+            no-nag -at "$t" || echo "ISSUES reported: $1 $t" >&2
+        fi
 
-                "/etc/apt/sources.list.d/pve-enterprise.sources"|\
-                "/etc/apt/sources.list.d/pbs-enterprise.sources"|\
-                "/etc/apt/sources.list.d/pmg-enterprise.sources"|\
-                "/etc/apt/sources.list.d/pve-enterprise.list"|\
-                "/etc/apt/sources.list.d/pbs-enterprise.list"|\
-                "/etc/apt/sources.list.d/pmg-enterprise.list")
-
-                    no-subscription -at "$t" || echo "ISSUES reported: $1 $2" >&2
-
-                ;;
-
-                "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"|\
-                "/usr/share/pve-manager/js/pvemanagerlib.js"|\
-                "/usr/share/pve-manager/touch/pvemanager-mobile.js"|\
-                "/usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js"|\
-                "/usr/share/javascript/pmg-gui/js/pmgmanagerlib.js")
-
-                    no-nag -at "$t" || echo "ISSUES reported: $1 $2" >&2
-
-                ;;
-
-            esac
-
-        done
-
+    done
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+abort-upgrade | abort-remove | abort-deconfigure)
+
+    :
     ;;
 
-    *) 
-        echo "ERROR: $0 - unknown argument: $1" >&2
-        exit 1
+*)
+
+    echo "ERROR: ${0##*/} - unknown argument: $1" >&2
+    exit 1
     ;;
+
 esac
diff --git a/free-pmx-no-subscription/bin/no-subscription b/free-pmx-no-subscription/bin/no-subscription
--- a/free-pmx-no-subscription/bin/no-subscription
+++ b/free-pmx-no-subscription/bin/no-subscription
@@ -1,80 +1,101 @@
 #!/bin/bash
 
+# SPDX-FileCopyrightText: Copyright 2025 free-pmx
 # SPDX-License-Identifier: AGPL-3.0-only
-
-echo
-echo "free-pmx: NO-SUBSCRIPTION - 'No Subscription' Repositories Setup"
-trap "echo" EXIT
 
 declare -i status=0
 
-source "/usr/lib/free-pmx/no-subscription-common" 2> /dev/null \
-|| { echo "Internal error, aborting." >&2; exit 1; }
+source "/usr/lib/free-pmx/no-subscription-common" \
+    && init_out \
+    || exit 255
 
-init "FREE_PMX_NO_SUBSCRIPTION" "$@"
+print OUT
+print OUT "free-pmx: NO-SUBSCRIPTION - 'No Subscription' Repositories Setup"
+trap 'print OUT' EXIT
 
-{ declare_aptsrcs; declare -i err=$?; }
-(( err & 1 )) && { echo "Cannot gather necessary system information, aborting." >&2; exit 1; }
+init_run "FREE_PMX_NO_SUBSCRIPTION" "$@"
 
-{ declare -A todo_id_flags; for i in "${ORD_APTSRC_IDS[@]}"; do todo_id_flags["$i"]=0; done; }
+declare_ns_globals || {
+    print ERR "Cannot gather necessary system information, aborting."
+    exit 1
+}
+
+declare -A todo_id_flags
+declare id
+for id in "${APTSRC_ID_LIST[@]}"; do todo_id_flags[$id]=0; done
 
 if [[ -n $O_TARGET ]]; then
-    (( ${#ARGS[@]} == 0 )) \
-    || { echo "Arguments not allowed when used with '-t' option." >&2; exit 1; }
+    ((${#ARGS[@]} == 0)) || {
+        print ERR "Arguments not allowed when used with '-t' option."
+        exit 1
+    }
 
-    declare list_id_match=''
-
-    for i in "${!APTSRC_TARGETS[@]}"; do
-        [[ $O_TARGET == "${APTSRC_TARGETS["$i"]}" ]] \
-        && { list_id_match="$i"; todo_id_flags["$i"]=1; break; }
-    done
-
-    if [[ -n $list_id_match ]]; then
-        echo "Explicit target recognised as $list_id_match: $O_TARGET"
+    declare id="${APTSRC_TARGET_TO_ID[$O_TARGET]}"
+    if [[ -n $id ]]; then
+        print OUT "Explicit target recognised."
+        todo_id_flags[$id]=1
     else
-        { echo "No defined repositories for this target." >&2; exit 1; }
+        print ERR "No defined repositories for this target."
+        ((status |= 1))
     fi
-elif (( ${#ARGS[@]} > 0 )); then
+elif ((${#ARGS[@]} > 0)); then
+    declare arg
     for arg in "${ARGS[@]}"; do
-        case "$arg" in
-            pve|pbs|pmg|ceph) todo_id_flags["$arg"]=1;;
-            *) { echo "Invalid argument: $arg" >&2; exit 1; };;
-        esac
+        [[ -v APTSRC_ID_TO_TARGET[$arg] ]] || {
+            print ERR "Invalid argument: $arg"
+            exit 1
+        }
+
+        todo_id_flags[$arg]=1
     done
 else
     echo -n "Detecting default sources ..."
-    for i in "${ORD_APTSRC_IDS[@]}"; do
-        [[ -f ${APTSRC_TARGETS["$i"]} ]] && todo_id_flags["$i"]=1 && echo -n " $i"
+    declare id
+    for id in "${APTSRC_ID_LIST[@]}"; do
+        [[ -f ${APTSRC_ID_TO_TARGET[$id]} ]] && todo_id_flags[$id]=1 && echo -n " $id"
     done
-    echo        
-fi
-
-{ todo_count=0; for i in "${ORD_APTSRC_IDS[@]}"; do (( todo_count+=todo_id_flags[$i] )); done; }
-done_count=0
-
-if (( todo_count > 0 )); then
-    (( todo_id_flags["ceph"] == 1 )) && [[ -z $FREE_PMX_CEPH ]] \
-    && { todo_id_flags["ceph"]=0; echo "Ceph codename not configured, skipping ..." >&2; }
-
-    for i in "${ORD_APTSRC_IDS[@]}"; do
-        (( todo_id_flags["$i"] == 1 )) \
-        && echo "Setting up for $i ..." \
-        && run_rl_replace "${APTSRC_TARGETS["$i"]}" "${APTSRC_TEMPLS["$i"]}" \
-        && (( done_count++ ))
-    done
-    (( done_count != todo_count )) && status=1
-
-    echo "Completed total $done_count of $todo_count."
     echo
-
-    echo "Checking for Proxmox release key: $FREE_PMX_APTKEY_LOCAL ..."
-    run_rk_check "$FREE_PMX_APTKEY_LOCAL" "$FREE_PMX_APTKEY_ORIGIN" \
-    || { echo "Failed Proxmox release key check." >&2; status=1; }
-else
-    echo "Nothing to be set up."
 fi
 
-(( O_AUTORUN == 0 )) && (( done_count > 0 )) && cat << 'EOF'
+declare -i todo_count=0 done_count=0
+declare id
+for id in "${APTSRC_ID_LIST[@]}"; do ((todo_count += todo_id_flags[$id])); done
+
+if ((todo_count > 0)); then
+    ((todo_id_flags[ceph])) && [[ -z $FREE_PMX_CEPH ]] && {
+        print ERR "Ceph codename not configured, skipping ..."
+        todo_id_flags[ceph]=0
+    }
+
+    declare id
+    for id in "${APTSRC_ID_LIST[@]}"; do
+        ((todo_id_flags[$id])) \
+            && print OUT "Setting up for $id ..." \
+            && run_aptsrc_replace "${APTSRC_ID_TO_TARGET[$id]}" "${APTSRC_ID_TO_TEMPL[$id]}" \
+            && ((done_count++))
+    done
+    ((done_count == todo_count)) || ((status |= 1))
+
+    print OUT "Completed total $done_count of $todo_count."
+
+    print OUT
+
+    print OUT "Checking for Proxmox release key ..."
+
+    if [[ $FREE_PMX_APTKEY == "$FREE_PMX_APTKEY_LOCAL" ]]; then
+        run_aptkey_check "$FREE_PMX_APTKEY_LOCAL" "$FREE_PMX_APTKEY_ORIGIN" || {
+            print ERR "Failed Proxmox release key check."
+            ((status |= 1))
+        }
+    else
+        print OUT "Skipped - custom key specified: $FREE_PMX_APTKEY"
+    fi
+else
+    print OUT "Nothing to be set up."
+fi
+
+! ((O_AUTORUN)) && ((done_count > 0)) \
+    && print ERR $'\e' << EOF
 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 NOTICE: Do not forget to perform UPDATE and UPGRADE, e.g.:
@@ -82,11 +103,12 @@ NOTICE: Do not forget to perform UPDATE and UPGRADE, e.g.:
     apt full-upgrade
 EOF
 
-(( O_AUTORUN == 0 )) && cat << 'EOF'
+! ((O_AUTORUN)) \
+    && print ERR $'\e' << EOF
 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-Visit <https://free-pmx.pages.dev/tools/free-pmx-no-subscription/>
+Visit $NS_WEB
 for more details, to check the latest version or to report an issue.
 EOF
 
-exit $status
+exit $((status))
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common b/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common
--- a/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/no-subscription-common
@@ -1,140 +1,189 @@
+#!/bin/bash
+
+# SPDX-FileCopyrightText: Copyright 2025 free-pmx
 # SPDX-License-Identifier: AGPL-3.0-only
 
-source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
-|| { echo "Internal error, aborting." >&2; exit 1; }
+source "/usr/lib/free-pmx/no-subscription-util" \
+    || exit 255
 
 declare_common() {
 
-      declare -rg NS_CONFIG="/etc/free-pmx/no-subscription.conf"
+    : "${NS_WEB} ${NS_CONFIG}"
+
+    declare -rg NS_WEB="<https://free-pmx.pages.dev/tools/free-pmx-no-subscription/>"
+    declare -rg NS_CONFIG="/etc/free-pmx/no-subscription.conf"
 
 }
 
-declare_aptsrcs() {
+declare_ns_globals() {
 
-      declare -rg ORD_APTSRC_IDS=("pve" "pbs" "pmg" "ceph")
+    : "${APTSRC_ID_LIST} ${APTSRC_ID_TO_TARGET} ${APTSRC_TARGET_TO_ID} ${APTSRC_ID_TO_TEMPL}"
 
-      declare -A os_release
-      source_kv "/etc/os-release" os_release VERSION_ID VERSION_CODENAME \
-      && check_kv_allset os_release VERSION_ID VERSION_CODENAME \
-      || return 1
+    declare -rg APTSRC_ID_LIST=(pve pbs pmg ceph)
 
-      [[ ${os_release[VERSION_ID]} =~ ^[0-9]+$ ]] || return 1
-      declare -r formats=(sources list)
-      declare -rg APTSRC_FORMAT="${formats[(( os_release[VERSION_ID] < 13 ))]}"
+    declare -ra os_release_vars=(VERSION_ID VERSION_CODENAME)
+    declare -A os_release
+    source_kv "/etc/os-release" os_release "${os_release_vars[@]}" \
+        && check_kv_allset os_release "${os_release_vars[@]}" \
+        || return 1
 
-      declare -r list_d="/etc/apt/sources.list.d"
+    [[ ${os_release[VERSION_ID]} =~ ^[0-9]+$ ]] || return 1
+    declare -r ext_formats=(sources list)
+    declare -r ext="${ext_formats[((os_release[VERSION_ID] < 13))]}"
 
-      declare -rgA APTSRC_TARGETS=(
-            ["pve"]="$list_d/pve-enterprise.$APTSRC_FORMAT"
-            ["pbs"]="$list_d/pbs-enterprise.$APTSRC_FORMAT"
-            ["pmg"]="$list_d/pmg-enterprise.$APTSRC_FORMAT"
-            ["ceph"]="$list_d/ceph.$APTSRC_FORMAT"
-      )
+    declare -r aptsrc_d="/etc/apt/sources.list.d"
 
-      declare -r templ_d="/usr/share/free-pmx/no-subscription-aptsrcs"
+    declare -rgA APTSRC_ID_TO_TARGET=(
+        [pve]="$aptsrc_d/pve-enterprise.$ext"
+        [pbs]="$aptsrc_d/pbs-enterprise.$ext"
+        [pmg]="$aptsrc_d/pmg-enterprise.$ext"
+        [ceph]="$aptsrc_d/ceph.$ext"
+    )
 
-      declare -rgA APTSRC_TEMPLS=(
-            ["pve"]="$templ_d/pve-no-subscription.$APTSRC_FORMAT.template"
-            ["pbs"]="$templ_d/pbs-no-subscription.$APTSRC_FORMAT.template"
-            ["pmg"]="$templ_d/pmg-no-subscription.$APTSRC_FORMAT.template"
-            ["ceph"]="$templ_d/ceph-no-subscription.$APTSRC_FORMAT.template"
-      )
+    declare -gA APTSRC_TARGET_TO_ID=()
+    declare id
+    for id in "${!APTSRC_ID_TO_TARGET[@]}"; do APTSRC_TARGET_TO_ID[${APTSRC_ID_TO_TARGET[$id]}]="$id"; done
+    declare -rg APTSRC_TARGET_TO_ID
 
-      declare -rgx FREE_PMX_DEBIAN="${os_release[VERSION_CODENAME]}"
-      declare -rgx FREE_PMX_CEPH
+    declare -r templ_d="/usr/share/free-pmx/no-subscription-aptsrcs"
 
-      declare -rgx FREE_PMX_APTKEY_SHARE="/usr/share/keyrings/proxmox-archive-keyring.gpg"
-      declare -rgx FREE_PMX_APTKEY_LOCAL="/etc/apt/keyrings/proxmox-release-$FREE_PMX_DEBIAN.gpg"
-      declare -rgx FREE_PMX_APTKEY_ORIGIN="https://enterprise.proxmox.com/debian/proxmox-release-$FREE_PMX_DEBIAN.gpg"
+    declare -rgA APTSRC_ID_TO_TEMPL=(
+        [pve]="$templ_d/pve-no-subscription.$ext.template"
+        [pbs]="$templ_d/pbs-no-subscription.$ext.template"
+        [pmg]="$templ_d/pmg-no-subscription.$ext.template"
+        [ceph]="$templ_d/ceph-no-subscription.$ext.template"
+    )
+
+    declare -rgx FREE_PMX_DEBIAN="${os_release[VERSION_CODENAME]}"
+    declare -rgx FREE_PMX_CEPH
+
+    declare -rgx FREE_PMX_APTKEY_ORIGIN="https://enterprise.proxmox.com/debian/proxmox-release-$FREE_PMX_DEBIAN.gpg"
+    declare -rgx FREE_PMX_APTKEY_LOCAL="/etc/apt/keyrings/proxmox-release-$FREE_PMX_DEBIAN.gpg"
+
+    declare -rgx FREE_PMX_APTKEY=${FREE_PMX_APTKEY:-$FREE_PMX_APTKEY_LOCAL}
 
 }
 
-declare_patchdefs() {
+declare_nn_globals() {
 
-      declare -i err=0
+    : "${PATCHDEF_ID_PREFIX_LIST} ${PATCHDEF_TARGET_LIST} ${PATCHDEF_TARGET_TO_IDS} ${PATCHDEF_DIR}"
 
-      declare -rga AVAIL_PATCH_TARGETS=(
-            "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
-            "/usr/share/pve-manager/js/pvemanagerlib.js"
-            "/usr/share/pve-manager/touch/pvemanager-mobile.js"
-            "/usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js"
-            "/usr/share/javascript/pmg-gui/js/pmgmanagerlib.js"
-      )
+    declare -i err=0
 
-      declare -rg PATCHDEF_DIR="/usr/share/free-pmx/no-nag-patchdefs"
+    declare -rga PATCHDEF_ID_PREFIX_LIST=(pwt pve pbs pmg)
 
-      declare -ga ORD_PATCHDEF_IDS=()
-      declare -gA PATCHDEF_TARGETS
+    declare -ga PATCHDEF_TARGET_LIST=()
+    declare -gA PATCHDEF_TARGET_TO_IDS=()
 
-      for p in "${PATCHDEF_DIR}/"*.patchdef; do
+    declare -rg PATCHDEF_DIR="/usr/share/free-pmx/no-nag-patchdefs"
+
+    declare id_prefix patchdef
+    for id_prefix in "${PATCHDEF_ID_PREFIX_LIST[@]}"; do
+        for patchdef in "$PATCHDEF_DIR/$id_prefix"*.patchdef; do
             declare -A pd
-            source_kv "$p" pd TARGET || { err=$(( err | 1 )); continue; }
-            [ -z "${pd[TARGET]}" ] && { err=$(( err | 2 )); continue; }
+            source_kv "$patchdef" pd TARGET || {
+                ((err |= 1))
+                continue
+            }
+            [ -n "${pd[TARGET]}" ] || {
+                ((err |= 2))
+                continue
+            }
 
-            if [[ "$p" =~ ^${PATCHDEF_DIR}/(.*)\.patchdef ]]; then            
-                  declare m=${BASH_REMATCH[1]}
-                  ORD_PATCHDEF_IDS+=("$m")
-                  PATCHDEF_TARGETS["$m"]="${pd[TARGET]}" 
-            fi
-      done
+            [[ "$patchdef" =~ ^${PATCHDEF_DIR}/(.*)\.patchdef ]] && {
+                declare id=${BASH_REMATCH[1]}
+                [[ -v PATCHDEF_TARGET_TO_IDS[${pd[TARGET]}] ]] \
+                    || PATCHDEF_TARGET_LIST+=("${pd[TARGET]}")
+                PATCHDEF_TARGET_TO_IDS[${pd[TARGET]}]+="$id;"
+            }
+        done
+    done
 
-      declare -rg ORD_PATCHDEF_IDS
-      declare -rg PATCHDEF_TARGETS
+    declare -rg PATCHDEF_TARGET_LIST
+    declare -rg PATCHDEF_TARGET_TO_IDS
 
-      return $err
-
-}
-
-init() {
-
-      declare -r conf_opt_check="$1"
-      shift
-
-      declare_common
-
-      source "$NS_CONFIG" 2> /dev/null ||:
-
-      declare -gi O_AUTORUN=0
-      declare -g O_TARGET=''
-      declare -ga ARGS=()
-
-      declare -i opt_t_multiple=0
-      declare -i opt_invalid=0
-
-      while getopts ":at:" opt; do
-      case "$opt" in
-            a) O_AUTORUN=1;;
-            t) [[ -z $O_TARGET ]] || opt_t_multiple=1; O_TARGET=$OPTARG;;
-            *) opt_invalid=1;;
-      esac
-      done
-
-      case "${!conf_opt_check}" in
-      prohibit)
-            { echo "Prohibited by configuration: $NS_CONFIG" >&2; exit; };;
-      manual)
-            (( O_AUTORUN == 0 )) \
-            || { echo "Not configured to auto-run - option '$conf_opt_check': $NS_CONFIG" >&2; exit; };;
-      auto)
-            (( O_AUTORUN == 1 )) \
-            && echo "Automatic run.";;
-      *)
-            { echo "Configuration invalid or missing: $NS_CONFIG" >&2; exit 1; };;
-      esac
-
-      (( opt_t_multiple == 0 )) \
-      || { echo "Multiple '-t' options not supported."; exit 1; }
-      (( opt_invalid == 0 )) \
-      || { echo "Invalid command option." >&2; exit 1; }
-
-      { shift $((OPTIND-1)); while (($# > 0)); do ARGS+=("$1"); shift; done; }
-
-      declare -rg O_AUTORUN
-      declare -rg O_TARGET
-      declare -rg ARGS
+    return $((err))
 
 }
 
-run_rl_replace() { /usr/lib/free-pmx/repo-list-replace "$@"; }
-run_rk_check() { /usr/lib/free-pmx/repo-key-check "$@"; }
-run_pd_apply() { /usr/lib/free-pmx/patchdef-apply "$@"; }
+init_run() {
+
+    : "${O_AUTORUN} ${O_TARGET} ${ARGS}"
+
+    [[ -n $1 ]] && declare -r conf_opt_check="$1" || return 255
+    shift
+
+    declare_common
+
+    source "$NS_CONFIG" || :
+
+    declare -gi O_AUTORUN=0
+    declare -g O_TARGET=''
+    declare -ga ARGS=()
+    declare -i opt_invalid=0
+
+    while getopts ":at:" opt; do
+        case "$opt" in
+        a)
+            O_AUTORUN=1
+            ;;
+        t)
+            [[ -z $O_TARGET ]] || opt_invalid=1
+            O_TARGET=$OPTARG
+            [[ -n $O_TARGET ]] || opt_invalid=1
+            ;;
+        *)
+            opt_invalid=1
+            ;;
+        esac
+    done
+
+    declare -rg O_AUTORUN
+    declare -rg O_TARGET
+
+    ! ((opt_invalid)) || {
+        print ERR "Invalid command option(s)."
+        exit 1
+    }
+
+    shift $((OPTIND - 1))
+    while (($# > 0)); do
+        ARGS+=("$1")
+        shift
+    done
+
+    declare -rg ARGS
+
+    case "${!conf_opt_check}" in
+    prohibit)
+        print ERR "Prohibited by configuration: $NS_CONFIG"
+        exit 0
+        ;;
+    manual)
+        ! ((O_AUTORUN)) || {
+            print ERR "Not configured to auto-run - option '$conf_opt_check': $NS_CONFIG"
+            exit 0
+        }
+        ;;
+    auto)
+        ((O_AUTORUN)) && print OUT "Automatic run."
+        ;;
+    *)
+        print ERR "Configuration invalid or missing: $NS_CONFIG"
+        exit 1
+        ;;
+    esac
+
+}
+
+run_aptkey_check() {
+    /usr/lib/free-pmx/aptkey-check "$@"
+}
+
+run_aptsrc_replace() {
+    /usr/lib/free-pmx/aptsrc-replace "$@"
+}
+
+run_patchdef_apply() {
+    /usr/lib/free-pmx/patchdef-apply "$@"
+}
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply b/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply
--- a/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/patchdef-apply
@@ -1,61 +1,80 @@
 #!/bin/bash
 
+# SPDX-FileCopyrightText: Copyright 2025 free-pmx
 # SPDX-License-Identifier: AGPL-3.0-only
 
-source "/usr/lib/free-pmx/no-subscription-util" 2> /dev/null \
-|| { echo "Internal error, aborting." >&2; exit 1; }
-
 declare -i status=0
+
+source "/usr/lib/free-pmx/no-subscription-util" \
+    && init_out \
+    || exit 255
 
 [[ -n $1 ]] && declare -r patchdef=$1 || exit 1
 declare -r bak_ext=$2
 
+declare -ra pd_vars=(DISPLAY TARGET PACKAGE SINCE)
 declare -A pd
-source_kv "$patchdef" pd DISPLAY TARGET PACKAGE SINCE \
-&& check_kv_allset pd DISPLAY TARGET PACKAGE SINCE \
-|| { echo "! Corrupt patch definition: $patchdef" >&2; exit $(( status | 1 )); }
+source_kv "$patchdef" pd "${pd_vars[@]}" \
+    && check_kv_allset pd "${pd_vars[@]}" \
+    || {
+        print ERR "! Corrupt patch definition: $patchdef"
+        exit $((status |= 1))
+    }
 
-[[ -f ${pd[TARGET]} ]] \
-|| { echo "! File to patch not present for: ${pd[DISPLAY]}" >&2; exit $(( status | 2 )); }
+[[ -f ${pd[TARGET]} ]] || {
+    print ERR "! File to patch not present for: ${pd[DISPLAY]}"
+    exit $((status |= 2))
+}
 
-declare pd_version
-pd_version=$(deb_last_le_version "${pd[PACKAGE]}" "${pd[SINCE]}") \
-|| { echo "! Cannot determine appropriate patch version: $patchdef" >&2; exit $(( status | 4 )); }
+declare pver
+pver=$(deb_last_le_version "${pd[PACKAGE]}" "${pd[SINCE]}") || {
+    print ERR "! Cannot determine appropriate patch version: $patchdef"
+    exit $((status |= 4))
+}
 
-declare pd_partial="${patchdef%*.patchdef}.$pd_version"
+[[ ${patchdef##*/} =~ ^([a-z]+-[0-9]+)- ]]
+declare pid_prefix=${BASH_REMATCH[1]}
+declare pdesc="[$pid_prefix|$pver] ${pd[DISPLAY]}"
 
-declare -A pd_rawblock
-slurp "$pd_partial".orig 'pd_rawblock[ORIG]' \
-&& slurp "$pd_partial".repl 'pd_rawblock[REPL]' \
-|| { echo "! Error loading patch partials: $pd_partial.{orig,repl}" >&2; exit $(( status | 4 )); }
+declare pblock="${patchdef%*.patchdef}.$pver"
+
+declare -A _praw
+slurp "$pblock".orig '_praw[ORIG]' && slurp "$pblock".repl '_praw[REPL]' \
+    || {
+        print ERR "! Error loading patch raw blocks: $pdesc"
+        exit $((status |= 4))
+    }
 
 if [[ -n $bak_ext ]]; then
-    cp "${pd[TARGET]}"{,."$bak_ext"} 2> /dev/null \
-    || echo "! Unable to make a '.$bak_ext' copy: ${pd[TARGET]}" >&2
+    cp "${pd[TARGET]}"{,."$bak_ext"} || {
+        print ERR "! Unable to make a '.$bak_ext' copy: ${pd[TARGET]}"
+    }
 fi
 
 declare tfile checksum_prior checksum_after
 
 checksum_prior=$(checksum "${pd[TARGET]}")
 
-{
-tfile=$(mktemp /tmp/free_pmx_patched_XXXXXX) \
-&& chmod 644 "$tfile" \
-&& subst_rawblock pd_rawblock < "${pd[TARGET]}" > "$tfile" \
-&& mv -f "$tfile" "${pd[TARGET]}"; \
-} 2> /dev/null \
-|| { echo "! Error during patch application: ${pd[DISPLAY]}" >&2; exit $(( status | 2 )); }
+: \
+    && tfile=$(mktemp "${pd[TARGET]}"-patched-XXXXXX) \
+    && chmod 644 "$tfile" \
+    && subst_rawblock _praw < "${pd[TARGET]}" > "$tfile" \
+    && mv -f "$tfile" "${pd[TARGET]}" \
+    || {
+        print ERR "! Error during patch application: $pdesc"
+        exit $((status |= 2))
+    }
 
 checksum_after=$(checksum "${pd[TARGET]}")
 
 if [[ -z $checksum_prior ]] || [[ -z $checksum_after ]]; then
-    echo "? Unknown result: ${pd[DISPLAY]}"
-    status=$(( status | 4 ))
+    print OUT "? Unknown result: $pdesc"
+    ((status |= 4))
 elif [[ $checksum_prior == "$checksum_after" ]]; then
-    echo "- NO effect: ${pd[DISPLAY]}"
-    status=$(( status | 8 ))
+    print OUT "- NO effect: $pdesc"
+    ((status |= 8))
 else
-    echo "+ OK: ${pd[DISPLAY]}"
+    print OUT "+ OK: $pdesc"
 fi
 
-exit $status
+exit $((status))
